server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: file:./src/main/resources/myConfig